name = "taskora"
main = "server.js"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

# 🚀 تفعيل خدمة الملفات الثابتة (HTML, CSS, Images)
[assets]
directory = "./public"

# إعداد المهمة المجدولة (Cron)
[triggers]
crons = ["* * * * *"]
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "67988f0e9c144cf1848bc6f4a49a9083"
